// 左側導航
var outlookbar=new outlook();
var t;
t = outlookbar.addtitle('基本形狀', '基本形狀', 1)
outlookbar.additem('圓形', t, '../BasicType/BasicType.aspx?type=circle')
outlookbar.additem('橢圓形', t, '../BasicType/BasicType.aspx?type=ellipse')
outlookbar.additem('矩形', t, '../BasicType/BasicType.aspx?type=rect')
outlookbar.additem('多邊形', t, '../BasicType/BasicType.aspx?type=polygon')
outlookbar.additem('折線', t, '../BasicType/BasicType.aspx?type=polyline')
outlookbar.additem('Marker', t, '../BasicType/BasicType.aspx?type=marker')
outlookbar.additem('Pattern', t, '../BasicType/BasicType.aspx?type=pattern')
outlookbar.additem('老虎', t, '../BasicType/BasicType.aspx?type=tiger')
outlookbar.additem('发电站', t, '../BasicType/BasicType.aspx?type=PowerStation')
outlookbar.additem('地图', t, '../BasicType/BasicType.aspx?type=map')
outlookbar.additem('Pattern文字', t, '../BasicType/BasicType.aspx?type=pattern1')

t = outlookbar.addtitle('漸變', '漸變', 1)
outlookbar.additem('線性漸變', t, '../Gradiental/GradImage.aspx?type=lingrad')
outlookbar.additem('輻射漸變', t, '../Gradiental/GradImage.aspx?type=radgrad')
outlookbar.additem('透明', t, '../Gradiental/GradImage.aspx?type=opacity')
outlookbar.additem('面具', t, '../Gradiental/GradImage.aspx?type=mask')
outlookbar.additem('背景', t, '../Gradiental/GradImage.aspx?type=background')


t = outlookbar.addtitle('濾鏡', '濾鏡', 1)
outlookbar.additem('feColorMatrix濾鏡', t, '../FeChange/FeSVGImage.aspx?type=feColorMatrix')
outlookbar.additem('feComponentTransfer濾鏡', t, '../FeChange/FeSVGImage.aspx?type=feComponentTransfer')
outlookbar.additem('feComposite濾鏡', t, '../FeChange/FeSVGImage.aspx?type=feComposite')
outlookbar.additem('feImage濾鏡', t, '../FeChange/FeSVGImage.aspx?type=feImage')
outlookbar.additem('felend濾鏡', t, '../FeChange/FeSVGImage.aspx?type=felend')
outlookbar.additem('feMorphology濾鏡', t, '../FeChange/FeSVGImage.aspx?type=feMorphology')
outlookbar.additem('feTurbulence濾鏡', t, '../FeChange/FeSVGImage.aspx?type=feTurbulence')
outlookbar.additem('濾鏡示例1', t, '../FeChange/FeSVGImage.aspx?type=filters00')
outlookbar.additem('濾鏡示例2', t, '../FeChange/FeSVGImage.aspx?type=filters01')
outlookbar.additem('濾鏡示例3', t, '../FeChange/FeSVGImage.aspx?type=filters02')

t = outlookbar.addtitle('動畫', '動畫', 1)
outlookbar.additem('animate元素', t, '../SVGAnimate/AnimSVGImage.aspx?type=animate')
outlookbar.additem('animateMotion元素', t, '../SVGAnimate/AnimSVGImage.aspx?type=animateMotion')
outlookbar.additem('animateTransform元素', t, '../SVGAnimate/AnimSVGImage.aspx?type=animateTransform')
outlookbar.additem('set元素', t, '../SVGAnimate/AnimSVGImage.aspx?type=set')
outlookbar.additem('花朵1', t, '../SVGAnimate/AnimSVGImage.aspx?type=flower')
outlookbar.additem('花朵2', t, '../SVGAnimate/AnimSVGImage.aspx?type=flowerSvg')
//outlookbar.additem('旋轉', t, '../SVGAnimate/AnimSVGImage.aspx?type=roate')
outlookbar.additem('剪切路徑', t, '../SVGAnimate/AnimSVGImage.aspx?type=clipPath')
outlookbar.additem('動態增加動點', t, '../SVGAnimate/AnimSVGImage.aspx?type=DynamicAddPoints')
outlookbar.additem('劃線', t, '../SVGAnimate/AnimSVGImage.aspx?type=DrawLine')
outlookbar.additem('畫比賽尔曲線', t, '../SVGAnimate/AnimSVGImage.aspx?type=Bezier2')
outlookbar.additem('漂亮的刀', t, '../SVGAnimate/AnimSVGImage.aspx?type=knife')
outlookbar.additem('隨鼠標移動', t, '../SVGAnimate/AnimSVGImage.aspx?type=MoveWithMouse')
outlookbar.additem('俄羅斯方塊', t, '../SVGAnimate/AnimSVGImage.aspx?type=blockGame')
outlookbar.additem('動態Graphics', t, '../SVGAnimate/AnimSVGImage.aspx?type=graphs30')
outlookbar.additem('水面文字', t, '../SVGAnimate/AnimSVGImage.aspx?type=ripples6')
outlookbar.additem('天空下星星', t, '../SVGAnimate/AnimSVGImage.aspx?type=stars3')
outlookbar.additem('氣球', t, '../SVGAnimate/AnimSVGImage.aspx?type=balloon')

t = outlookbar.addtitle('傳遞參數', '傳遞參數', 1)
outlookbar.additem('旋轉', t, '../SVGAnimate/Rotate/roate.html')
outlookbar.additem('龜裂浮動效果', t, '../SVGDataPass/PassData.html')
outlookbar.additem('依參數構造SVG', t, '../SVGDataPass/PassDataPage.aspx')
outlookbar.additem('化學元素', t, '../ShowSVGPage/Default.aspx')
outlookbar.additem('Chart圖表', t, '../SVGGraphic/GraphicCtrl.aspx')

//t=outlookbar.addtitle('','',1)
//outlookbar.additem('',t,'loginout.php')